# Generated by Django 5.0.6 on 2024-07-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="orgId",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
